Squashed commit of the following:
commit 4a5d9746ff081e226677c9b17569c60738e1157e
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Wed Mar 28 02:46:59 2018 -0700

    1.1.0 release

commit 7be822345bbdd2fed0ee651fb214988d32f63620
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Wed Mar 28 02:10:23 2018 -0700

    Squashed commit of the following:

    commit 814109abb9f0fd8f16d7067b726772dad71dcc53
    Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
    Date:   Tue Mar 27 19:13:42 2018 -0700

        A version of lockss-core that builds without artifacts.lockss.org.

    commit 1c894def9164df87f41c1c7c52b3a5e2a8076993
    Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
    Date:   Tue Mar 27 13:10:53 2018 -0700

        Start removing dependency on Artifactory

commit 4ca112c32cc24c396a54440486444a3147718aa1
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Tue Mar 27 15:43:46 2018 -0700

    Dependency on lockss-util 1.6.0 and laaws-repository-core 1.11.0.

commit 7a2e9c4d4cfc03b64950dad4e1b51069c73874c8
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Tue Mar 27 04:34:01 2018 -0700

    Reverting to Artifactory versions of JoSQL and GentlyWEB-Utils.

commit d8dce469a9e7aed76150d875074adcf73cad1b1a
Merge: b462241 17e5284
Author: Tom Lipkis <tal@pss.com>
Date:   Tue Mar 27 01:07:35 2018 -0700

    Merge branch 'feature-RestRepository' into develop

commit 17e52841048f58eab9dc223af53a069c28278dae
Author: Tom Lipkis <tal@pss.com>
Date:   Tue Mar 27 00:28:31 2018 -0700

    Cosmetic

commit 5bcd520cdbe9867a790672f2f1a6a19cb3cf92f2
Author: Tom Lipkis <tal@pss.com>
Date:   Tue Mar 27 00:01:25 2018 -0700

    Up to laaws-repository-core-1.10.0.  Adjust version, size, digest, sort

commit adafdd26c4568c2c9885413f8896a8f3998fd0ab
Author: Tom Lipkis <tal@pss.com>
Date:   Mon Mar 26 23:45:00 2018 -0700

    Up to laaws-repository-core-1.10.0

commit cdae8b1e02e40401e37eeed295cb17cde1e8d3a0
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Mon Mar 26 04:33:19 2018 -0700

    Resolve NoClassDefFoundError on org.json.JSONObject, surfaced in FuncCuLayer when a local: repository was used.

commit 017c272effd57287264a0d9876de24db4fe2f6ab
Author: Tom Lipkis <tal@pss.com>
Date:   Sun Mar 25 22:36:52 2018 -0700

    Merge

commit f1aabd9c66d7320e502d729aa770878a5161e9d0
Author: Tom Lipkis <tal@pss.com>
Date:   Sun Mar 25 22:29:35 2018 -0700

    Use "V2" for new repo.  Many bug fixes, mostly feature complete

commit 7eb993553e3cb9891d5446f52787975d17370257
Author: Tom Lipkis <tal@pss.com>
Date:   Sun Mar 25 22:28:09 2018 -0700

    Use "V2" for new repo.  Many bug fixes, mostly feature complete

commit efb3cc407dea5a884f9b1dc07674836bddc400d6
Author: Tom Lipkis <tal@pss.com>
Date:   Sun Mar 25 22:27:48 2018 -0700

    Added TAGS

commit b462241f25e819ba5d510afaa3ff95b4fed0588b
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Sat Mar 24 09:56:19 2018 -0700

    Remove dependency on Artifactory for GentlyWEB-Utils (now coming in from
    org.lockss:josql 2.2-p1).

commit 473065e19666b09d47341eb87c1a3bf889ba65c6
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Sat Mar 24 09:51:36 2018 -0700

    Remove dependency on Artifactory for JoSQL (and GentlyWEB-Utils).

commit b938f85028c08041eaf4ddb28d64ca1e210417b0
Author: fergaloy <fergaloy@stanford.edu>
Date:   Fri Mar 23 15:24:04 2018 -1000

    Fixed build by adding missing import.

commit 5c43308a671332ff0cb2352aa3e3b7fa9101419f
Author: Tom Lipkis <tal@pss.com>
Date:   Fri Mar 23 13:02:40 2018 -0700

    Added beginning of functional tests for CU layer using new repository

commit 6bb6c48746d27eef2523c39553ace3f58d070b8e
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Fri Mar 23 11:26:12 2018 -0700

    Remove dependency on Artifactory for ICU4J, PDFBox 0.7.3.

commit 3f9575e584189e6e9d7255debf3b73024ee3e9ea
Author: Tom Lipkis <tal@pss.com>
Date:   Fri Mar 23 01:29:07 2018 -0700

    Added SimpleNewRepoV3TestCase

commit e825060c7b9ee36df2f06d0716ae556cd87d6eda
Author: Tom Lipkis <tal@pss.com>
Date:   Fri Mar 23 01:28:06 2018 -0700

    o.l.plugin.registryJars now a glob pattern

commit ad82c309bca99f60f7d01e674d825ddc010a6659
Author: Tom Lipkis <tal@pss.com>
Date:   Fri Mar 23 00:56:32 2018 -0700

    Add logging of stack trace where actually thrown

commit 3f25a098efb0c65add861d7878df45b4e8b55edf
Author: Tom Lipkis <tal@pss.com>
Date:   Fri Mar 23 00:55:40 2018 -0700

    NPE avoidance

commit 79727c748d8a2fbab04a3eed255ddcbc3d3303c2
Author: Tom Lipkis <tal@pss.com>
Date:   Fri Mar 23 00:55:03 2018 -0700

    Fixed logger name

commit f4d2a64c8c0a6862f6881966f5f108dfeca0ac13
Author: Tom Lipkis <tal@pss.com>
Date:   Fri Mar 23 00:53:29 2018 -0700

    Use repository-core-1.8, delete artifact.lockss.org

commit 8259a95164a23f53e3c6a978ef38c49a68e4eb8c
Author: Tom Lipkis <tal@pss.com>
Date:   Fri Mar 23 00:52:55 2018 -0700

    Integrated new repository (mostly)

commit 73dca0aed0176b7b08a0c284e512ac89e7a1f22b
Author: Tom Lipkis <tal@pss.com>
Date:   Fri Mar 23 00:51:29 2018 -0700

    Fixes test jar name

commit 817261f3aca832ed5829231e8873505d3177a6cd
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Thu Mar 22 16:04:29 2018 -0700

    Replacing patched JAR on our Artifactory with patched JAR on Maven Central

commit b0143d4d353e6d1127092a8aa323affa0266c05e
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Thu Mar 22 15:41:11 2018 -0700

    Now that lockss-tdbxml-maven-plugin 1.1.0 is on Maven Central, remove Artifactory from the <pluginManagement> section

commit 6fa38301f26b030f4c1a60a6292a69baf8c804b5
Author: Tom Lipkis <tal@pss.com>
Date:   Wed Mar 21 22:17:34 2018 -0700

    Moved old REST clients out of the way

commit 6cbc55030b407ad5f85b53602706edbff4ad5e32
Author: Tom Lipkis <tal@pss.com>
Date:   Wed Mar 21 22:12:25 2018 -0700

    Eliminate RestConfigFile test failures

commit 3dc672e4e5b012badab149f007695333b1415797
Author: Tom Lipkis <tal@pss.com>
Date:   Wed Mar 21 22:10:41 2018 -0700

    One more LockssRepository... -> OldLockssRepository...

commit f6085f48ac32100b56f38587a4e32c498b1e4de3
Author: Tom Lipkis <tal@pss.com>
Date:   Wed Mar 21 21:39:28 2018 -0700

    Partition getAuFromId() calls into that and new getAuFromIdIfExists()

commit e5c432085fa920923c6281b28259a3aa2dfb398f
Author: Tom Lipkis <tal@pss.com>
Date:   Wed Mar 21 20:08:41 2018 -0700

    Added Delete button to DebugPanel

commit 3121e29cca679b4ffa13d65f6ee277836b21c73d
Author: Tom Lipkis <tal@pss.com>
Date:   Wed Mar 21 20:06:11 2018 -0700

    Up version to 1.2.0-SNAPSHOT, use laaws-repository-core 1.6.0

commit 2ed2d16eac3ec358315d226878651a33bc37c698
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Wed Mar 21 05:09:50 2018 -0700

    Upgrade to lockss-tdbxml-maven-plugin 1.1.0.

commit 53835815084a5098a27b924543b367636c35687d
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Wed Mar 21 05:09:32 2018 -0700

    Unnecessary file.

commit bc4391bd3d01ec9b7098a7817359e59eced2be83
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Wed Mar 21 04:58:33 2018 -0700

    TDB tools moved to lockss-tdb-tools; lockss-tdbxml-maven-plugin 1.1.0 knows to use lockss-tdb-tools on its
    own.

commit abf4a15d952f4ba36b32499883314b4af33ab6dd
Author: Tom Lipkis <tal@pss.com>
Date:   Mon Mar 19 21:06:07 2018 -0700

    Added laaws-repository-core dependency, mechanism to specify a global LockssRepository

commit 09bc8f397f965283c0688c1ca242bd2702519bd2
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Sat Mar 17 22:02:08 2018 -0700

    Renamed class named in a string

commit edc9b1f86fb749a1e3f1d54b93dc0a1360836163
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Tue Mar 13 13:56:04 2018 -0700

    Renamed from LockssRepository to OldLockssRepository, from LockssRepositoryImpl to
    OldLockssRepositoryImpl.

commit 6350a0a20b4ab3d694e12f8b8ec394ee432ff6c9
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Mon Mar 12 17:45:57 2018 -0700

    Proper patched version in Maven Central (not a patched JAR dropped in
    our Artifactory). Used to build the recipe for forking from GitHub and
    patching to Maven Central.

commit 9a44779e929422af8c8ff25aed540574de183509
Author: Claire Griffin <clairetg@stanford.edu>
Date:   Wed Mar 7 13:57:57 2018 -0800

    Squashed commit of the following:

    commit 177fe3e1813a992bf7a6b565ec74b208d8aa8891
    Author: Claire Griffin <clairetg@stanford.edu>
    Date:   Wed Mar 7 13:57:28 2018 -0800

        add getPoll utility method for PollerService

commit 1bf6b5b7b4761a69bf88e644a41ff1c542ceb202
Merge: 530c917 78bc62b
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Wed Mar 7 12:42:12 2018 -0800

    Merge tag 'version-1.0.0' into develop

    lockss-core version 1.0.0

commit 530c917351530b05df571f42576fc80a73445a32
Author: Thib Guicherd-Callin <thib@cs.stanford.edu>
Date:   Wed Mar 7 12:24:09 2018 -0800

    Begin 1.1.0-SNPASHOT cycle.